export const mobgnblistitems = [
  {
    id: 1,
    name: "My Starbucks",
    itemList: [
      { id: 1, name: "한눈에 보기", isList: false },
      { id: 2, name: "My 리워드", isList: true },
      { id: 3, name: "My 스타벅스 카드", isList: true },
      { id: 4, name: "My 스타벅스 e-Gift Card", isList: true },
      { id: 5, name: "My 쿠폰", isList: true },
      { id: 6, name: "My 캘린더", isList: false },
      { id: 7, name: "My 메뉴", isList: false },
      { id: 8, name: "My 고객의 소리", isList: false },
      { id: 9, name: "전자영수증", isList: false },
      { id: 10, name: "개인컵 리워드 설정", isList: false },
      { id: 11, name: "My DT Pass", isList: false },
      { id: 12, name: "개인정보관리", isList: true },
    ],
  },
  {
    id: 2,
    name: "COFFEE",
    itemList: [
      { id: 1, name: "한눈에 보기", isList: false },
      { id: 2, name: "커피", isList: true },
      { id: 3, name: "커피 이야기", isList: true },
      { id: 4, name: "스타벅스 리저브", isList: true },
      { id: 5, name: "에스프레소 음료", isList: true },
      { id: 6, name: "최상의 커피를 즐기는 법", isList: true },
    ],
  },
  {
    id: 3,
    name: "MENU",
    itemList: [
      { id: 1, name: "한눈에 보기", isList: false },
      { id: 2, name: "음료", isList: true },
      { id: 3, name: "푸드", isList: true },
      { id: 4, name: "상품", isList: true },
      { id: 5, name: "카드", isList: true },
      { id: 6, name: "메뉴 이야기", isList: true },
    ],
  },
  {
    id: 4,
    name: "STORE",
    itemList: [
      { id: 1, name: "한눈에 보기", isList: false },
      { id: 2, name: "매장 찾기", isList: true },
      { id: 3, name: "드라이브 스루 매장", isList: false },
      { id: 4, name: "스타벅스 리저브 매장", isList: false },
      { id: 5, name: "커뮤니티 스토어 매장", isList: false },
    ],
  },
  {
    id: 5,
    name: "RESPONSIBILITY",
    itemList: [
      { id: 1, name: "한눈에 보기", isList: false },
      { id: 2, name: "사회공헌 캠페인 소개", isList: false },
      { id: 3, name: "지역 사회 참여 활동", isList: true },
      { id: 4, name: "환경보호 활동", isList: true },
      { id: 5, name: "윤리 구매", isList: true },
      { id: 6, name: "글로벌 사회 공헌", isList: true },
    ],
  },
  {
    id: 6,
    name: "Starbucks Rewards",
    itemList: [
      { id: 1, name: "한눈에 보기", isList: false },
      { id: 2, name: "스타벅스 리워드", isList: true },
      { id: 3, name: "스타벅스 카드", isList: true },
      { id: 4, name: "스타벅스 e-Gift Card", isList: true },
    ],
  },
  {
    id: 7,
    name: "CORPORATE SALES",
    itemList: [
      { id: 1, name: "단체 및 기업 구매 안내", isList: false },
      { id: 2, name: "단체 주문 배달 안내", isList: true },
    ],
  },
  {
    id: 8,
    name: "WHAT'S NEW",
    itemList: [
      { id: 1, name: "한눈에 보기", isList: false },
      { id: 2, name: "이벤트", isList: true },
      { id: 3, name: "뉴스", isList: true },
      { id: 4, name: "매장별 이벤트", isList: true },
      { id: 5, name: "공지사항", isList: false },
      { id: 6, name: "월페이퍼", isList: false },
    ],
  },
];
